spring:
  profiles:
    active: default
---
spring:
  profiles: default
server:
  port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: cloud
server:
  port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: http://sc-eureka-server.azurewebsites.net
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://sc-eureka-server.azurewebsites.net/eureka/
#http://${eureka.instance.hostname}:${server.port}/eureka/