spring:
  profiles:
    active: development
---
spring:
  profiles: development
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: INFO
    com.jci: DEBUG  
---
spring:
  profiles: cloud
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
