spring:
  profiles:
    active: default
---
spring:
  profiles: development
server:
  port: 8083 
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/xml,application/json
feign:
  compression:
    min-request-size: 1024
    mime-types: application/xml,application/json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: INFO
    com.jci: DEBUG  
---
spring:
  profiles: default
#server:
#  port: 8083
 # compression:
  #  enabled: true
   # min-response-size: 1024
    #mime-types: application/xml,application/json
#feign:
#  compression:
#    min-request-size: 1024
#    mime-types: application/xml,application/json

eureka:
  client:
    serviceUrl:
      defaultZone: http://sc-eureka-server.azurewebsites.net/eureka/
