spring:
  profiles:
    active: development
---
spring:
  profiles: development
server:
  port: 8090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: cloud
server:
  port: 8090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
